### ISSUE TITLE
Mathjax not supported

### ISSUE THREAD

**Issue by pratyakshs** [python-gsoc/gsoc#5]

**Comment by terriko** [comment]
The software we're using is Planet Venus https://github.com/rubys/venus -- Please report issues there, or if they're already fixed there, feel free to suggest that we upgrade our copy of planet venus.  Short term, you can put a note in your blog post that it may not show up well in the aggregator and folk interested in the details should click through.

Alas, with so many students and org admins who are unpaid volunteers with day jobs, we simply don't have the resources to handle software bugfixes ourselves.  I wish it were otherwise!

**Comment by terriko** [comment]
We're switching to a new blogging system this year, so the issue with planet venus is no longer applicable.  Closing this.
